//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramAPI.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramAPI.Test.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyC.
        /// </summary>
        public static string CopyC {
            get {
                return ResourceManager.GetString("CopyC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutC.
        /// </summary>
        public static string CutC {
            get {
                return ResourceManager.GetString("CutC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteC.
        /// </summary>
        public static string DeleteC {
            get {
                return ResourceManager.GetString("DeleteC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateC.
        /// </summary>
        public static string DuplicateC {
            get {
                return ResourceManager.GetString("DuplicateC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteC.
        /// </summary>
        public static string PasteC {
            get {
                return ResourceManager.GetString("PasteC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AllC.
        /// </summary>
        public static string Select_AllC {
            get {
                return ResourceManager.GetString("Select_AllC", resourceCulture);
            }
        }
    }
}
