//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleB.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyB.
        /// </summary>
        public static string CopyB {
            get {
                return ResourceManager.GetString("CopyB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutB.
        /// </summary>
        public static string CutB {
            get {
                return ResourceManager.GetString("CutB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteB.
        /// </summary>
        public static string DeleteB {
            get {
                return ResourceManager.GetString("DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateB.
        /// </summary>
        public static string DuplicateB {
            get {
                return ResourceManager.GetString("DuplicateB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteB.
        /// </summary>
        public static string PasteB {
            get {
                return ResourceManager.GetString("PasteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All B.
        /// </summary>
        public static string Select_AllB {
            get {
                return ResourceManager.GetString("Select_AllB", resourceCulture);
            }
        }
    }
}
