<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Avalonia" Version="8.1.97.11073" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AppModules\Infrastructure\Infrastructure.Interfaces\Infrastructure.Interfaces.csproj" />
    <ProjectReference Include="..\..\Games\Game.Domain\Game.Domain.csproj" />
    <ProjectReference Include="..\..\Games\Game.Infrastructure.Interfaces\Game.Infrastructure.Interfaces.csproj" />
    <ProjectReference Include="..\GameSender.Infrastructure.Interfaces\GameSender.Infrastructure.Interfaces.csproj" />
    <ProjectReference Include="..\GameSender.Infrastructure\GameSender.Infrastructure.csproj" />
  </ItemGroup>

</Project>
